ASSIGNMENT4_SRC = ./src/assignment4.c
ASSIGNMENT4 = ./target/assignment4

$(ASSIGNMENT4): $(ASSIGNMENT4_SRC)
	gcc -Wall -g $(ASSIGNMENT4_SRC) -o $(ASSIGNMENT4) -lpthread

clear: $(ASSIGNMENT4)
	rm -rf $(ASSIGNMENT4)
