./target/ask3: ./src/ask3.c
	gcc -Wall -g ./src/ask3.c -o ./target/ask3

./target/bin_creator: ./src/bin_creator.c
	gcc -Wall -g ./src/bin_creator.c -o ./target/bin_creator

./target/is_sorted: ./src/is_sorted.c
	gcc -Wall -g ./src/is_sorted.c -o ./target/is_sorted