ASSIGNMENT2_SRC = ./src/assignment2.c
ASSIGNMENT2 = ./target/assignment2

$(ASSIGNMENT2): $(ASSIGNMENT2_SRC)
	gcc -Wall -g $(ASSIGNMENT2_SRC) -o $(ASSIGNMENT2) -lpthread

clear: $(ASSIGNMENT2)
	rm -rf $(ASSIGNMENT2)
