./target/ask4: ./src/ask4.c ../assignment1/target/libmysem.a
	gcc -Wall -g ./src/ask4.c -o ./target/ask4 -lpthread -lmysem -L../assignment1/target

clear: ./target/assignment4
	rm -rf ./target/assignment4